# Autogenerated with k2tf from https://raw.githubusercontent.com/DataDog/datadog-agent/master/Dockerfiles/manifests/agent.yaml

resource "kubernetes_daemonset" "datadog_agent" {
  count = "${var.dd_enable}"

  metadata {
    name      = "datadog-agent"
    namespace = "default"
  }

  spec {
    template {
      metadata {
        name = "datadog-agent"

        labels {
          app = "datadog-agent"
        }
      }

      spec {
        volume {
          name = "dockersocket"

          host_path {
            path = "/var/run/docker.sock"
          }
        }

        volume {
          name = "procdir"

          host_path {
            path = "/proc"
          }
        }

        volume {
          name = "cgroups"

          host_path {
            path = "/sys/fs/cgroup"
          }
        }

        volume {
          name = "s6-run"
        }

        container {
          name  = "datadog-agent"
          image = "datadog/agent:${var.image_version}"

          port {
            name           = "dogstatsdport"
            container_port = 8125
            protocol       = "UDP"
          }

          port {
            name           = "traceport"
            container_port = 8126
            protocol       = "TCP"
          }

          env {
            name  = "DD_API_KEY"
            value = "${var.dd_api_key}"
          }

          env {
            name  = "KUBERNETES"
            value = "true"
          }

          env {
            name  = "DD_HEALTH_PORT"
            value = "5555"
          }

          env {
            name = "DD_KUBERNETES_KUBELET_HOST"

            value_from {
              field_ref {
                field_path = "status.hostIP"
              }
            }
          }

          resources {
            limits {
              memory = "256Mi"
              cpu    = "200m"
            }

            requests {
              cpu    = "200m"
              memory = "256Mi"
            }
          }

          volume_mount {
            name       = "dockersocket"
            mount_path = "/var/run/docker.sock"
          }

          volume_mount {
            name       = "procdir"
            read_only  = true
            mount_path = "/host/proc"
          }

          volume_mount {
            name       = "cgroups"
            read_only  = true
            mount_path = "/host/sys/fs/cgroup"
          }

          volume_mount {
            name       = "s6-run"
            mount_path = "/var/run/s6"
          }

          liveness_probe {
            http_get {
              path = "/health"
              port = "5555"
            }

            initial_delay_seconds = 15
            timeout_seconds       = 5
            period_seconds        = 15
            success_threshold     = 1
            failure_threshold     = 3
          }

          image_pull_policy = "Always"
        }

        service_account_name = "datadog-agent"
      }
    }
  }
}
